"""Shared fixtures: one fitted real module, and synthetic modules with known answers.

The synthetic modules matter more than the real one. A datasheet gives four
points and no ground truth for the five parameters, so fitting one can only be
checked against the points it was fitted to. A synthetic module is built the
other way round - choose the five parameters, generate the datasheet they
imply, then fit it - which gives an exact answer to compare against.
"""

from __future__ import annotations

import pytest

from single_diode.curves import characteristic_points
from single_diode.datasheet import CS5P_220M, Datasheet
from single_diode.extract import extract
from single_diode.model import DiodeParameters, thermal_voltage
from single_diode.translate import REFERENCE_TEMPERATURE_C, celsius_to_kelvin, translate

# (name, cells in series, ideality factor, IL, I0, Rs, Rsh)
SYNTHETIC_SPECS = [
    ("small_36cell", 36, 1.10, 8.20, 2.0e-10, 0.22, 180.0),
    ("standard_60cell", 60, 1.20, 9.40, 5.0e-10, 0.35, 420.0),
    ("standard_72cell", 72, 1.05, 9.80, 8.0e-11, 0.30, 550.0),
    ("large_96cell", 96, 1.25, 5.20, 3.0e-10, 1.05, 340.0),
    ("low_shunt", 60, 1.15, 9.00, 4.0e-10, 0.40, 60.0),
    ("high_series", 72, 1.10, 9.50, 2.0e-10, 0.95, 500.0),
]


def make_parameters(
    cells_in_series: int,
    ideality: float,
    photocurrent: float,
    saturation_current: float,
    r_series: float,
    r_shunt: float,
    temperature_c: float = REFERENCE_TEMPERATURE_C,
) -> DiodeParameters:
    """Build a parameter set from physically meaningful inputs."""
    return DiodeParameters(
        photocurrent=photocurrent,
        saturation_current=saturation_current,
        resistance_series=r_series,
        resistance_shunt=r_shunt,
        thermal_voltage=thermal_voltage(
            ideality, cells_in_series, celsius_to_kelvin(temperature_c)
        ),
    )


def make_datasheet(
    name: str,
    params: DiodeParameters,
    cells_in_series: int,
    alpha_sc: float = 0.004,
    delta_t: float = 1.0,
) -> Datasheet:
    """Generate the datasheet a given parameter set would produce.

    The four operating points come from the model. ``beta_oc`` is measured the
    same way the extraction will later impose it: translate to a slightly
    warmer cell and difference the open-circuit voltages. Using the same
    definition on both sides is deliberate - it means a round trip tests the
    solver, not the definition of the coefficient.
    """
    point = characteristic_points(params)
    warm = translate(
        params,
        irradiance=1000.0,
        temperature_c=REFERENCE_TEMPERATURE_C + delta_t,
        alpha_sc=alpha_sc,
    )
    beta_oc = (characteristic_points(warm).v_oc - point.v_oc) / delta_t

    return Datasheet(
        name=name,
        i_sc=point.i_sc,
        v_oc=point.v_oc,
        i_mp=point.i_mp,
        v_mp=point.v_mp,
        alpha_sc=alpha_sc,
        beta_oc=beta_oc,
        cells_in_series=cells_in_series,
        source="synthetic, generated by tests/conftest.py from known parameters",
    )


@pytest.fixture(scope="session")
def datasheet() -> Datasheet:
    """The one real module: published values, no ground-truth parameters."""
    return CS5P_220M


@pytest.fixture(scope="session")
def fitted(datasheet: Datasheet) -> DiodeParameters:
    """Parameters fitted to the real module, reused across tests."""
    return extract(datasheet).parameters


@pytest.fixture(scope="session")
def synthetic_cases() -> list[tuple[str, Datasheet, DiodeParameters, int]]:
    """Datasheets with exactly known parameters behind them."""
    cases = []
    for name, ns, n, il, i0, rs, rsh in SYNTHETIC_SPECS:
        params = make_parameters(ns, n, il, i0, rs, rsh)
        cases.append((name, make_datasheet(name, params, ns), params, ns))
    return cases


@pytest.fixture(scope="session")
def reference_params() -> DiodeParameters:
    """A single well-behaved parameter set for solver-level tests."""
    return make_parameters(60, 1.2, 9.4, 5.0e-10, 0.35, 420.0)
